version: '2'
services:
  mysql:
    build: ./mysql
    environment:
      MYSQL_DATABASE: flask
      MYSQL_USER: flask
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - db:/var/lib/mysql
  python:
    build: ./python
    ports:
      - '5000:5000'
    volumes:
      - ./python/docker_entry:/usr/src/docker_entry
      - ./python/supsnap:/usr/src/supsnap
    command: bash ./docker_entry/entrypoint.sh
    depends_on:
      - mysql
volumes:
  db:
